{{- if .Values.chatService.ingress.enabled -}}
{{- $fullName := include "chat-service.fullname" . -}}
{{- $svcPort := .Values.chatService.service.restPort -}}
{{- if and .Values.global.ingressClassNameVersion .Values.chatService.ingress.ingressClassNameVersion }}
  {{- if not (eq .Values.chatService.ingress.ingressClassNameVersion "v1") }}
  {{- if not .Values.chatService.ingress.ingressClassName }}
  {{- $_ := set .Values.chatService.ingress "ingressClassName" .Values.global.ingressClassName }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
  {{- with .Values.chatService.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.global.ingressClassNameVersion .Values.chatService.ingress.ingressClassNameVersion }}
  {{- if eq .Values.chatService.ingress.ingressClassNameVersion "v1" }}
  ingressClassName: {{ .Values.chatService.ingress.ingressClassName }}
  {{- else }}
  {{- if .Values.chatService.ingress.ingressClassName }}
  ingressClassName: {{ .Values.chatService.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.chatService.ingress.tls }}
  tls:
    {{- range .Values.chatService.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.chatService.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (eq (lower .pathType) "implementation-specific") }}
            pathType: ImplementationSpecific
            {{- else if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
