apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-starter-grpc.fullname" . }}
  labels:
    {{- include "go-starter-grpc.labels" . | nindent 4 }}
  {{- with .Values.app.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-starter-grpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-starter-grpc.selectorLabels" . | nindent 8 }}
      {{- with .Values.app.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-starter-grpc.serviceAccountName" . }}
      {{- with .Values.app.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.app.service.grpcPort }}
              protocol: TCP
            - name: rest
              containerPort: {{ .Values.app.service.restPort }}
              protocol: TCP
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.secrets.postgresql.enabled }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: {{ .Values.secrets.postgresql.secretKeys.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: {{ .Values.secrets.postgresql.secretKeys.password }}
            {{- end }}
            {{- if .Values.secrets.redis.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: {{ .Values.secrets.redis.secretKeys.password }}
            {{- end }}
            {{- if .Values.secrets.jwt.enabled }}
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-jwt-secrets
                  key: {{ .Values.secrets.jwt.secretKeys.accessTokenSecret }}
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-jwt-secrets
                  key: {{ .Values.secrets.jwt.secretKeys.refreshTokenSecret }}
            {{- end }}
          volumeMounts:
            - name: storage-migrations
              mountPath: /root/storage/migrations
              readOnly: true
      volumes:
        - name: storage-migrations
          configMap:
            name: {{ include "go-starter-grpc.fullname" . }}-migrations
