apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-starter-grpc.fullname" . }}-env
  labels:
    {{- include "go-starter-grpc.labels" . | nindent 4 }}
data:
  # Application configuration
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_PORT: {{ .Values.env.APP_PORT | quote }}
  REST_PORT: {{ .Values.env.REST_PORT | quote }}
  
  # Database configuration
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  
  # JWT Configuration
  JWT_EXPIRATION_TIME: {{ .Values.env.JWT_EXPIRATION_TIME | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.env.JWT_REFRESH_EXPIRATION | quote }}
  
  # TLS Configuration
  TLS_ENABLED: {{ .Values.env.TLS_ENABLED | quote }}
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: {{ .Values.env.RATE_LIMIT_ENABLED | quote }}
  RATE_LIMIT_REQUESTS: {{ .Values.env.RATE_LIMIT_REQUESTS | quote }}
  RATE_LIMIT_WINDOW: {{ .Values.env.RATE_LIMIT_WINDOW | quote }}
  
  # Security Headers
  SECURITY_HEADERS_ENABLED: {{ .Values.env.SECURITY_HEADERS_ENABLED | quote }}
  HSTS_MAX_AGE: {{ .Values.env.HSTS_MAX_AGE | quote }}
  
  # Logging Configuration
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  LOG_JSON_FORMAT: {{ .Values.env.LOG_JSON_FORMAT | quote }}
  
  # Server Timeouts
  HEALTH_CHECK_TIMEOUT: {{ .Values.env.HEALTH_CHECK_TIMEOUT | quote }}
  SERVER_READ_TIMEOUT: {{ .Values.env.SERVER_READ_TIMEOUT | quote }}
  SERVER_WRITE_TIMEOUT: {{ .Values.env.SERVER_WRITE_TIMEOUT | quote }}
