{{- if .Values.app.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "go-starter-grpc.fullname" . }}
  labels:
    {{- include "go-starter-grpc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "go-starter-grpc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.app.service.restPort }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: go-starter-grpc
      ports:
        - protocol: TCP
          port: {{ .Values.app.service.grpcPort }}
        - protocol: TCP
          port: {{ .Values.app.service.restPort }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
